version: "3.7"

services:
    app:
        image: ambientum/php:8.1-nginx
        container_name: yinyang_php
        volumes:
            - .:/var/www/app
        ports:
            - "8080:8080"
        links:
            - database

    database:
        image: mysql:8
        container_name: yinyang_db
        environment:
            MYSQL_DATABASE: "yinyang_database"
            MYSQL_USER: "teste"
            MYSQL_PASSWORD: "yinyang"
            MYSQL_ROOT_PASSWORD: "yinyang1"
        ports:
            - "3306:3306"
        volumes:
            - ./docker/docker/mysql:/var/lib/mysql