name: Deploy to Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Display directory contents
      run: |
        dir
        
    - name: Install dependencies
      run: | 
        cd front-end
        npm install 
        npm run build
        
    - name: Display directory contents
      run: |
        dir

    - name: Copy files to server
      run: |
        # Install WinSCP
        choco install winscp -y

        # Define the WinSCP script content
        $winscpScript = @"
        open sftp://${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
        lcd Yin-Yang/front-end/build
        cd C:/TG/teste/
        put *.*
        exit
        "@

        # Save the script to a file
        $winscpScriptPath = "winscp-script.txt"
        $winscpScript | Out-File $winscpScriptPath -Encoding utf8

        # Run WinSCP with the script and specify the private key
        winscp.com /script=$winscpScriptPath /privatekey="${{ secrets.SSH_PRIVATE_KEY }}"

    - name: Restart IIS
      run: iisreset /restart
