name: Deploy to Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Display directory contents
      run: |
        dir
        
    - name: Install dependencies
      run: | 
        cd front-end
        npm install 
        npm run build
        
    - name: Display directory contents
      run: |
        dir

    - name: Deploy to Windows Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }} # Adicione se o seu servidor estiver usando uma porta diferente
        script: |
          # Comando para copiar os arquivos para o servidor Windows (por exemplo, usando o robocopy)
          robocopy $GITHUB_WORKSPACE\build "\\${{ secrets.SERVER_HOST }}\C$\Caminho\Para\Seu\Site" /MIR
