name: Deploy to Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.13
        
    - name: mudar diretorio
      run: | 
        cd Yin-Yang/front-end
        
    - name: Display directory contents
      run: |
        dir
        
    - name: Install dependencies
      run: | 
        cd Yin-Yang/front-end
        npm install 

    - name: Build React app
      run: |
        cd Yin-Yang/front-end
        npm run build

    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: "front-end/build/"  # ou o caminho do seu build
        target: "C:/TG/teste/"  # o caminho no seu servidor

    - name: Restart IIS
      run: iisreset /restart
